//=============================================================================
// File:         csv_route_sequence.sv
// Description:  CSV readers for AIS-based golden stimulus and expected data
//               (updated for dt_hex column and full 5-state golden)
//=============================================================================

`include "uvm_macros.svh"
import uvm_pkg::*;
import fusion_pkg::*;
import fusion_env_pkg::*;


//=============================================================================
// CLASS: golden_stimulus_reader
// Reads golden_stimulus.csv (generated by generate_golden.py from AIS data)
//
// Column order (19 cols):
//   step,timestamp,
//   gps_x_hex,gps_y_hex,gps_valid,
//   imu_psi_hex,imu_dot_hex,imu_valid,
//   odom_v_hex,odom_valid,
//   dt_hex,
//   gt_x,gt_y,
//   gps_x,gps_y,
//   imu_heading,imu_yaw_rate,odom_speed,dt
//=============================================================================

class golden_stimulus_reader;

    string csv_filename;
    bit    verbose;

    sensor_measurement measurements[$];
    logic [31:0] dt_hex_arr[$];   // FP32 dt per cycle for AXI REG_DT
    real gt_x_arr[$], gt_y_arr[$];
    real gps_x_arr[$], gps_y_arr[$];
    int total_lines;

    // First data row: CTRV x0 for state_mem words 0–4 (gps_x, gps_y, odom_speed, imu_heading, imu_yaw_rate)
    bit  init_state_valid;
    real init_x0, init_y0, init_speed0, init_heading0, init_yaw_rate0;

    function new(string filename = "golden_stimulus.csv");
        this.csv_filename = filename;
        this.verbose = 1'b0;
        this.total_lines = 0;
        this.init_state_valid = 1'b0;
    endfunction

    function logic [31:0] hex_to_u32(string s);
        logic [31:0] result;
        int rc;
        rc = $sscanf(s, "%h", result);
        return result;
    endfunction

    function int read_file();
        int fd, fgets_rc;
        string line;

        fd = $fopen(csv_filename, "r");
        if (fd == 0) begin
            $error("[GOLDEN_READER] Cannot open: %s", csv_filename);
            return 0;
        end

        if (!$feof(fd))
            fgets_rc = $fgets(line, fd);

        while (!$feof(fd)) begin
            fgets_rc = $fgets(line, fd);
            if (fgets_rc > 0)
                parse_line(line);
        end

        $fclose(fd);
        if (verbose)
            $display("[GOLDEN_READER] Read %0d entries from %s", total_lines, csv_filename);
        return total_lines;
    endfunction

    function void parse_line(string line);
        string fields[$];
        int num_fields;
        sensor_measurement meas;
        logic [31:0] gps_x_hex, gps_y_hex, imu_psi_hex, imu_dot_hex, odom_v_hex, dt_hex_val;
        int gps_valid_i, imu_valid_i, odom_valid_i;
        real gt_x_val, gt_y_val, gps_x_val, gps_y_val;

        split_csv(line, fields);
        num_fields = fields.size();
        if (num_fields < 19) return;

        // Columns 2-9: sensor hex
        gps_x_hex   = hex_to_u32(fields[2]);
        gps_y_hex   = hex_to_u32(fields[3]);
        gps_valid_i = fields[4].atoi();
        imu_psi_hex = hex_to_u32(fields[5]);
        imu_dot_hex = hex_to_u32(fields[6]);
        imu_valid_i = fields[7].atoi();
        odom_v_hex  = hex_to_u32(fields[8]);
        odom_valid_i= fields[9].atoi();

        // Column 10: dt_hex (FP32)
        dt_hex_val  = hex_to_u32(fields[10]);

        // Columns 11-14: ground truth and GPS float
        gt_x_val  = fields[11].atoreal();
        gt_y_val  = fields[12].atoreal();
        gps_x_val = fields[13].atoreal();
        gps_y_val = fields[14].atoreal();

        if (!init_state_valid) begin
            init_x0        = gps_x_val;
            init_y0        = gps_y_val;
            init_heading0  = fields[15].atoreal();
            init_yaw_rate0 = fields[16].atoreal();
            init_speed0    = fields[17].atoreal();
            init_state_valid = 1'b1;
        end

        meas = sensor_measurement::type_id::create("meas");
        meas.gps_data   = {gps_x_hex, gps_y_hex};
        meas.gps_valid  = (gps_valid_i != 0);
        meas.imu_data   = {imu_psi_hex, imu_dot_hex, 32'h0};
        meas.imu_valid  = (imu_valid_i != 0);
        meas.odom_data  = odom_v_hex;
        meas.odom_valid = (odom_valid_i != 0);
        meas.duration   = 1;

        measurements.push_back(meas);
        dt_hex_arr.push_back(dt_hex_val);
        gt_x_arr.push_back(gt_x_val);
        gt_y_arr.push_back(gt_y_val);
        gps_x_arr.push_back(gps_x_val);
        gps_y_arr.push_back(gps_y_val);

        total_lines++;
    endfunction

    function void split_csv(string str, ref string fields[$]);
        int last_pos;
        string field;
        fields.delete();
        last_pos = 0;
        forever begin
            int pos;
            pos = -1;
            for (int i = last_pos; i < str.len(); i++) begin
                if (str.getc(i) == ",") begin
                    pos = i;
                    break;
                end
            end
            if (pos == -1) begin
                if (last_pos < str.len()) begin
                    field = str.substr(last_pos, str.len() - 1);
                    fields.push_back(field);
                end
                break;
            end else begin
                if (pos > last_pos)
                    field = str.substr(last_pos, pos - 1);
                else
                    field = "";
                fields.push_back(field);
                last_pos = pos + 1;
            end
        end
    endfunction

    function sensor_measurement get_measurement(int index);
        if (index < 0 || index >= measurements.size()) return null;
        return measurements[index];
    endfunction

    function logic [31:0] get_dt_hex(int index);
        logic [31:0] h;
        if (index < 0 || index >= dt_hex_arr.size()) return 32'h3D23_D70A; // 0.04 s FP32
        h = dt_hex_arr[index];
        // REG_DT==0 is invalid for RTL predict; match Python main.py (dt<=0 → 1.0 s FP32)
        if (h == 32'h0) return 32'h3F80_0000;
        return h;
    endfunction

    function int get_count();
        return measurements.size();
    endfunction

    function void report();
        $display("\n================================================");
        $display("Golden Stimulus Report (AIS-based)");
        $display("================================================");
        $display("  File:        %s", csv_filename);
        $display("  Total rows:  %0d", total_lines);
        $display("================================================\n");
    endfunction

endclass: golden_stimulus_reader


//=============================================================================
// CLASS: golden_expected_reader
// Reads golden_expected.csv for Python UKF full 5-state estimates
//
// Column order (13 cols):
//   step,timestamp,
//   est_x,est_y,est_speed,est_heading,est_yaw_rate,
//   gt_x,gt_y,
//   gps_x,gps_y,
//   gps_error,ukf_sw_error
//=============================================================================

class golden_expected_reader;

    string csv_filename;
    real est_x_arr[$], est_y_arr[$];
    real est_speed_arr[$], est_heading_arr[$], est_yaw_rate_arr[$];
    real gt_x_arr[$], gt_y_arr[$];
    int total_lines;

    function new(string filename = "golden_expected.csv");
        this.csv_filename = filename;
        this.total_lines = 0;
    endfunction

    function int read_file();
        int fd, fgets_rc;
        string line;

        fd = $fopen(csv_filename, "r");
        if (fd == 0) begin
            $warning("[EXPECTED_READER] Cannot open: %s  (SW cross-check disabled)", csv_filename);
            return 0;
        end

        if (!$feof(fd))
            fgets_rc = $fgets(line, fd);

        while (!$feof(fd)) begin
            fgets_rc = $fgets(line, fd);
            if (fgets_rc > 0) begin
                string fields[$];
                split_csv(line, fields);
                if (fields.size() >= 9) begin
                    est_x_arr.push_back(fields[2].atoreal());
                    est_y_arr.push_back(fields[3].atoreal());
                    est_speed_arr.push_back(fields[4].atoreal());
                    est_heading_arr.push_back(fields[5].atoreal());
                    est_yaw_rate_arr.push_back(fields[6].atoreal());
                    gt_x_arr.push_back(fields[7].atoreal());
                    gt_y_arr.push_back(fields[8].atoreal());
                    total_lines++;
                end
            end
        end

        $fclose(fd);
        return total_lines;
    endfunction

    function void split_csv(string str, ref string fields[$]);
        int last_pos;
        string field;
        fields.delete();
        last_pos = 0;
        forever begin
            int pos;
            pos = -1;
            for (int i = last_pos; i < str.len(); i++) begin
                if (str.getc(i) == ",") begin
                    pos = i;
                    break;
                end
            end
            if (pos == -1) begin
                if (last_pos < str.len()) begin
                    field = str.substr(last_pos, str.len() - 1);
                    fields.push_back(field);
                end
                break;
            end else begin
                if (pos > last_pos)
                    field = str.substr(last_pos, pos - 1);
                else
                    field = "";
                fields.push_back(field);
                last_pos = pos + 1;
            end
        end
    endfunction

endclass: golden_expected_reader
